### ISSUE TITLE
Issues about  calculating mobility using EPW

### ISSUE THREAD

**Issue by qlyang94** [sponce24/EPW#3]
Dear Professeor:

	I am a new to EPW. I tried to repeat the calculation of mobility of your article (Towards  
predictive many-body calculations of phonon-limited carrier mobilities in semiconductors. Phys. Rev. B 97, 121201(R)). I am sorry that I have gotten few questions and I  really appreciate your answers. The electron mobility  and hole mobility of silicon are much smaller than your results. I am not sure whether the difference stems from the use of GW. I find that your group show many data of your published papers on  https://github.com/mmdg-oxford/papers.  I  really appreciate that you can share this paper's data. 

Best Regards,
QiaoLin Yang,
University of Chinese Academy of Sciences.

**Comment by sponce24** [comment]
Dear QiaoLin Yang,

The data of the PRB has been added to the group repo. 

Best wishes, 
Samuel
